[project]
name = "homework-22-django"
version = "0.1.0"
description = ""
authors = [
    {name = "alex_svch_777",email = "logger_77@mail.ru"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django (>=6.1.1,<7.0.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
lint = [
    "flake8 (>=7.3.0,<8.0.0)",
    "flake8-pyproject (>=1.2.4,<2.0.0)",
    "isort (>=9.0.1,<10.0.0)",
    "black (>=26.5.1,<27.0.0)"
]

[tool.flake8]
# Игнорировать ошибки (совместимость с Black)
extend-ignore = ["E203", "W503", "D203"]
# Максимальная длина строки
max-line-length = 119
# Исключить директории, которые есть в текущей структуре
exclude = [
    ".git",
    "__pycache__",
    ".venv",
    "**/migrations/*",
]
# Игнорировать правила для конкретных файлов проекта
per-file-ignores = [
    "config/__init__.py:F401",  # не ругаться на пустой или импортирующий init в config
    "config/settings.py:E501",  # игнорировать длинные секретные ключи и пути в настройках
]

[tool.black]
target-version = ['py314']
line-length = 119
exclude = '''
/(
    \.git
  | \.venv
  | migrations
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 119
skip = [".git", ".venv", "migrations"]